version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecertificate-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      # Mount application code and data folders for development
      # Only mount folders that exist to avoid errors
      - ./uploads:/app/uploads
      - ./generated_certificates:/app/generated_certificates
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PORT=5000
    networks:
      - ecertificate-network

networks:
  ecertificate-network:
    driver: bridge
