version: "3.9"
services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 "app:create_app()" --workers 3
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eCertificate
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./:/app
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
