name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image to ACR
      run: |
        az acr build --image e-certificate-app:${{ github.sha }} --registry $acr_name .
      env:
        acr_name: denxcertacr

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: denx-certificate-app
        resource-group-name: nexus-ai-rg
        images: 'denxcertacr.azurecr.io/e-certificate-app:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout